#!/usr/bin/env python
 
import os
from tkinter import *
#os.system("bspc rule -a Tk state=floating center=true")
os.system("bspc rule -a Tk state=floating")

class App:
  def __init__(self, master):
    frame = Frame(master)
    frame.pack()
    self.button1 = Button(frame, 
                         text="Allow Suspend", fg="red",
                         command=self.suspend_on)
    self.button1.pack(side=LEFT)
    self.button2 = Button(frame,
                         text="Do not Suspend",
                         command=self.suspend_off)
    self.button2.pack(side=LEFT)
    
  def suspend_on(self):
    os.system("killall systemd-inhibit")
  
  def suspend_off(self):
    os.system("systemd-inhibit --what=handle-lid-switch sleep 2592000 &")

root = Tk()
app = App(root)
root.mainloop()

